name: 🚀 Release
"on":
  push:
    branches:
      - main
  workflow_dispatch:
      

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Release
        uses: ridedott/release-me-action@master
        with:
          disable-changelog: true
