name: 🚀 Release
"on":
  push:
    branches:
      - main
  workflow_dispatch:
      

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: '0'
        
    - name: Bump version and push tag
      id: tag
      uses: Magikon/github-tag-action@master
      env:
        INITIAL_VERSION: 0.0.0
        RELEASE_BRANCHES: master
        TAG_CONTEXT: branch
        MAJOR: "BREAKING*CHANGE|*#major*"
        MINOR: "*feat*|*#minor*"
        PATCH: "*fix*|*chore*|*docs*|*update*"
        FORCE: true
        OVERWRITE: true
        
    - name: Echo variables
      env:
        NEW_TAG: ${{ steps.tag.outputs.new_tag }}
        SEL_TAG: ${{ steps.tag.outputs.tag }}
        PART: ${{ steps.tag.outputs.part }}
      run: |
        echo "New Tag"
        echo $NEW_TAG
        echo "Tag"
        echo $SEL_TAG
        echo "Part"
        echo $PART
