name: 🚀 Release
"on":
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
      - name: install semantic-release plugins
        run: npm install --no-save semantic-release-plugin-github-breaking-version-tag
      - name: write configuration
        run: |
          cat >.releaserc <<EOL
          {
            "branches": [
              "+([0-9]).x",
              "main",
              {
                "name": "beta",
                "prerelease": true
              }
            ],
            "plugins": [
              "@semantic-release/commit-analyzer",
              "@semantic-release/release-notes-generator",
              "semantic-release-plugin-github-breaking-version-tag",
              "@semantic-release/github"
            ]
          }
          EOL
      - name: Release the new version
        run: npx semantic-release --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
