name: 🚀 Release
"on":
  push:
    branches:
      - main
  workflow_dispatch:
      

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: 🤖 is-semantic-release
        uses: sebbo2002/action-is-semantic-pr@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
