name: 🚀 Release
"on":
  push:
    branches:
      - main
  workflow_dispatch:
      

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - id: semver-checkout
        name: 🤖 is-semantic-release
        uses: EasyDesk/action-semver-checkout@v1
      - name: Release
        if: ${{ steps.semver-checkout.outputs.should-release == 'true' }}
        uses: ./
        with:
          version: ${{ steps.semver-checkout.outputs.version }}
          prerelease: ${{ steps.semver-checkout.outputs.is-github-prerelease }}
