name: is-semantic-pr
on:
  - pull_request
workflow_dispatch:

jobs:
  release-bot:
    runs-on: ubuntu-latest
    steps:
      - name: 🤖 is-semantic-release
        uses: sebbo2002/action-is-semantic-pr@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
